main: com.martenm.parkour.MainClass
version: 1.0.3
name: Parkour
description: An parkour plugin
author: MartenM, Smither
softdepend: [LeaderHeads]

commands:
  parkour:
    description: Shows the parkour help.
    aliases: [pk]